return {
  {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    dependencies = {
      "nvim-treesitter/nvim-treesitter-textobjects",
      "nvim-treesitter/nvim-treesitter-context",
      "hiphish/rainbow-delimiters.nvim",
    },
    config = function()
      require("nvim-treesitter").setup({
        ensure_installed = {
          "lua",
          "python",
          "typescript",
          "javascript",
          "html",
          "css",
          "c",
          "cpp",
          "rust",
          "java",
          "jsx",
          "tsx",
          "json",
          "xml",
          "yaml",
          "kotlin",
          "groovy",
          "markdown",
          "markdown_inline",
          "go",
          "gomod",
          "gowork",
          "gosum",
          "c_sharp",
          "ruby",
          "php",
          "jsx",
          "tsx",
          "vimdoc",
          "dockerfile",
          "asm",
          "ruby",
          "bash",
          "powershell",
          "cmake",
          "make",
          "html_tags",
          "xml",
          "yaml",
          "json5",
          -- "nginx",
          "zig",
      },
        highlight = {
          enable = true,
          additional_vim_regex_highlighting = false,
        },
        indent = { enable = true },
        textobjects = {
          select = {
            enable = true,
            lookahead = true,
            keymaps = {
              ["af"] = "@function.outer",
              ["if"] = "@function.inner",
              ["ac"] = "@class.outer",
              ["ic"] = "@class.inner",
              ["al"] = "@loop.outer",
              ["il"] = "@loop.inner",
              ["aa"] = "@parameter.outer",
              ["ia"] = "@parameter.inner",
            },
          },
        },
      })
    end,
  }
}
